### ISSUE TITLE
All extensions are suddenly seemingly broken

### ISSUE THREAD

**Issue by anLizard** [kylejbrk/standard-notes-open-extended#7]
The new version might have broken this, not sure though.

![image](https://user-images.githubusercontent.com/48686356/114716025-f25ce800-9d33-11eb-86b4-094c89d9b0ab.png)

**Comment by kylejbrk** [comment]
Ah yea I see that.

I setup a custom domain for another project, and it seems to have affected all of my github pages projects. I'm not sure if this is intentional or not so I'll have to investigate.

For example if you go to: https://kylejbrk.github.io/standard-notes-open-extended/advanced-markdown-editor/dist/index.html 
it redirects to: https://kyleburke.net/standard-notes-open-extended/advanced-markdown-editor/dist/index.html

**Comment by kylejbrk** [comment]
Okay so I added the option to use a custom domain via 51ecfa11204085931373ccbae4250a867fd4a9fc

You might have to wait for the CDN to update, but it should be working after that.

**Comment by anLizard** [comment]
It's still happening on my end. Also made sure to try on a different browser, problem persists.

**Comment by kylejbrk** [comment]
@anLizard Can you please try using this url and see if your results are different?:
http://kyleburke.net/standard-notes-open-extended/

You have to activate it on the desktop app, and remember to reinstall your extensions.

**Comment by anLizard** [comment]
The link you provided doesn't display any extensions to install after activating.

However, after uninstalling all extensions, and using your old code again, I was able to reinstall my extensions and it works now!
Thanks!

**Comment by kylejbrk** [comment]
Did you activate it using the Desktop App? Either way glad it's working now.

**Comment by anLizard** [comment]
Activated it using the web app
